# Copyright 2020 The Atlas Authors. All rights reserved.

# General
verbose: true

# Service
service-address: ":10000"

# TLS
tls: false
#tls-cert-file: /path/to/cert-file
#tls-key-file: /path/to/key-file

# OAuth
oauth: false
#jwt-public-key-file: /path/to/key-file

# Kafka
brokers:
  - localhost:1234
topic: testtopic

# MinIO
# endpoint is an URL without scheme
endpoint: minio-internal-service:9000
# Whether to use https or http
secure: false
accessKeyID: minio
secretAccessKey: minio123
